# Work in Progress Configuration
name: "CARISMA Centre"
description: "Website coming soon"
url: ""
baseurl: ""

# Build Settings
markdown: kramdown

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - LICENSE
  - _people
  - _research
  - _publications
  - _news
